"""Pilot constants from BIZET OS 1.0 specification v0.9.

Values explicitly marked pilot must remain configurable and must not be scattered
through UI code.
"""
RULE_SET_VERSION = "1.0.0-pilot.6"

UNIT = "mm"
MODULE_GRID_STEP = 50
LOWER_CARCASS_DEPTH_HANDLE_PUSH = 560
LOWER_CARCASS_DEPTH_GOLA = 580
WORKTOP_DEPTH_DEFAULT = 600
UPPER_CARCASS_DEPTH_DEFAULT = 320
UPPER_CARCASS_DEPTH_BUILTIN_HOOD = 350
UPPER_BOTTOM_FROM_WORKTOP_DEFAULT = 600
UPPER_BOTTOM_LOW_USER_MIN = 500
UPPER_BOTTOM_LOW_USER_MAX = 550
UPPER_MODULE_MAX_HEIGHT = 1000
CEILING_INSTALL_TRAVEL_STRETCH_B = 20
FILLER_END = 18
FILLER_COMPENSATION = 40
WALL_DEVIATION_SCRIBE_MAX = 22
FREESTANDING_FRIDGE_L_FILLER = 40
FRIDGE_TOP_GAP_WITH_OVERHEAD = 50
COMMUNICATION_TOLERANCE_DEFAULT = 125
VISUAL_LINE_TOLERANCE_DEFAULT = 25
GAS_HOOD_BIZET_PILOT_MIN = 700
TALL_OVEN_BOTTOM_DRAWER_DEFAULT = 360
OVEN_NOMINAL_HEIGHT = 600
MICROWAVE_NOMINAL_HEIGHT = 450
PARTIAL_GOLA_GRIP_REVIEW = 125

# Open question OQ-01: conversation suggested ~350-400. Pilot uses 400 and traces it.
CUTLERY_TRAY_MODULE_WIDTH_PILOT = 400

# Candidate generator heuristic, not a furniture hard rule. All are on the 50 mm grid.
PREFERRED_HINGED_WIDTHS = [600, 550, 500, 450, 400, 350, 300]
MIN_SIMPLE_MODULE_WIDTH = 300

# Module Engine pilot search limits; implementation controls, not furniture rules.
MODULE_MAX_STANDARD_VARIANTS = 8
MODULE_MAX_NONSTANDARD_VARIANTS = 3
MODULE_MAX_CANDIDATES = 10
